export const createSuccessResponse = {
  id: "018f339a-e828-431d-98bf-a51758f28536",
  status: "DRAFT",
  productConfigurations: [
    {
      productId: "95554751-51d1-4f37-9785-417ae5251d56",
      initialDeposit: 1099,
      options: [
        {
          key: "loan_max_value",
          title: "Loan Max Value",
          category: "category",
          value: "Example",
        },
      ],
    },
  ],
  signers: [],
  createdAt: "2021-04-15T14:28:32.604Z",
  statusEmailBody: null,
  statusEmailSubject: null,
  statusUpdatedAt: null,
  statusUpdatedBy: null,
  branch: null,
  branchId: null,
  bsa: { risk: null, score: 0 },
  contract: { uri: null },
  contractDocumentCreatedAt: null,
  contractDocumentEnvelopeStatus: null,
  contractDocumentEnvelopeStatusUpdatedAt: null,
  verificationStatus: {
    faceStatus: "PENDING",
    documentStatus: "PENDING",
    addressStatus: "PENDING",
  },
};

export const updateSuccessResponse = {
  id: "018f339a-e828-431d-98bf-a51758f28536",
  status: "DRAFT",
  productConfigurations: [
    {
      productId: "95554751-51d1-4f37-9785-417ae5251d56",
      initialDeposit: 2000,
      options: [
        {
          key: "loan_max_value",
          title: "Loan Max Value",
          category: "category",
          value: "Example",
        },
      ],
    },
  ],
  signers: [],
  createdAt: "2021-04-15T14:28:32.604Z",
  statusEmailBody: null,
  statusEmailSubject: null,
  statusUpdatedAt: null,
  statusUpdatedBy: null,
  branch: null,
  branchId: null,
  bsa: { risk: null, score: 0 },
  contract: { uri: null },
  contractDocumentCreatedAt: null,
  contractDocumentEnvelopeStatus: null,
  contractDocumentEnvelopeStatusUpdatedAt: null,
  verificationStatus: {
    faceStatus: "PENDING",
    documentStatus: "PENDING",
    addressStatus: "PENDING",
  },
};

export const updateStatusSuccessResponse = {
  branch: null,
  branchId: null,
  bsa: { risk: null, score: 0 },
  contract: { uri: null },
  contractDocumentCreatedAt: null,
  contractDocumentEnvelopeStatus: null,
  contractDocumentEnvelopeStatusUpdatedAt: null,
  createdAt: "2021-04-15T14:28:32.604Z",
  id: "018f339a-e828-431d-98bf-a51758f28536",
  productConfigurations: [
    {
      productId: "95554751-51d1-4f37-9785-417ae5251d56",
      initialDeposit: 1099,
      options: [
        {
          key: "loan_max_value",
          title: "Loan Max Value",
          category: "category",
          value: "Example",
        },
      ],
    },
  ],
  signers: [],
  status: "INCOMPLETE",
  statusEmailBody: null,
  statusEmailSubject: null,
  statusUpdatedAt: null,
  statusUpdatedBy: null,
  verificationStatus: {
    faceStatus: "PENDING",
    documentStatus: "PENDING",
    addressStatus: "PENDING",
  },
};

export const getSuccessResponse = {
  id: "a6342816-7e89-4af6-a9e2-f0b22c947086",
  status: "INCOMPLETE",
  branchId: null,
  signers: [
    {
      role: "PRIMARY",
      id: "ebcdeded-b36c-4f84-bdf1-b10a9e12b8cc",
      status: "PENDING",
      firstName: "Hichelle",
      middleName: "",
      lastName: "Obama",
      address: "423432",
      city: "423423",
      state: "AL",
      zipCode: "43243243",
      phoneNumber: "(342) 342-3423",
      ssn: "342-43-2432",
      email: "sdaff@gadf.com",
      employer: "ding",
      dateOfBirth: "1964-01-17",
      emailVerified: false,
      emailVerifiedAt: null,
      consent: true,
      consentAccountOpening: true,
      consentPrivacyPolicy: true,
      consentCommunication: true,
      checkSanction: null,
      sanctionVerifiedAt: null,
      checkPoliticalExposure: null,
      politicalExposureVerifiedAt: null,
      checkAdverseMedia: null,
      adverseMediaVerifiedAt: null,
      checkAntiMoneyLaundering: null,
      antiMoneyLaunderingVerifiedAt: null,
      contractDocumentSignerStatus: null,
      contractDocumentSignerStatusUpdatedAt: null,
      invitedAt: "2021-04-16T09:00:40.208Z",
      idProofDocument: {
        type: "PASSPORT",
        number: "910239248",
        expirationDate: "2222-12-05",
        issuedDate: "1970-01-01",
        issuer: "USA",
        frontIdProof: {
          default: "someimage.png",
        },
        backIdProof: { default: null },
      },
      selfie: {
        default: "someimage.png",
      },
      verificationStatus: {
        faceStatus: "PENDING",
        faceUpdatedAt: "2021-04-16T09:00:40.208Z",
        documentStatus: "PENDING",
        documentUpdatedAt: "2021-04-16T09:00:40.208Z",
        addressStatus: "PENDING",
        addressUpdatedAt: "2021-04-16T09:00:40.208Z",
        sanctionsStatus: "PENDING",
        sanctionsUpdatedAt: "2021-04-16T09:00:40.208Z",
        mediaStatus: "PENDING",
        mediaUpdatedAt: "2021-04-16T09:00:40.208Z",
        politicalExposure: "PENDING",
        politicalExposureUpdatedAt: "2021-04-16T09:00:40.208Z",
      },
    },
  ],
  createdAt: "2021-04-16T09:00:39.654Z",
  statusUpdatedBy: null,
  statusUpdatedAt: null,
  statusEmailSubject: null,
  statusEmailBody: null,
  contractDocumentCreatedAt: "2021-04-16T09:00:47.815Z",
  contractDocumentEnvelopeStatus: "CREATED",
  contractDocumentEnvelopeStatusUpdatedAt: "2021-04-16T09:00:47.815Z",
  productConfigurations: [
    {
      productId: "3552ab85-08da-4bb5-be00-9e94d282d310",
      initialDeposit: 0,
      createdAt: "2021-04-16T09:00:39.680Z",
      product: {
        id: "3552ab85-08da-4bb5-be00-9e94d282d310",
        name: "Simple Checking",
        category: "CHECKING",
        sku: "simple-checking",
        summary:
          "Simple checking means no fees with online statements and it means no minimum balance required to maintain the account, access to online banking, bill pay and more. You get the benefits you want.",
        content:
          "<p>Simple checking <strong>lorem ipsum</strong> dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>\n<p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\n",
        createdAt: "2020-02-06T12:32:03.341Z",
        options: [
          {
            id: null,
            key: "account_number",
            category: "account_number",
            title: "Account Number",
            value: "DEMO105",
            lead: null,
            annotation: null,
            parentId: null,
          },
        ],
      },
    },
  ],
  branch: null,
  contract: { uri: null },
  verificationStatus: {
    faceStatus: "PENDING",
    documentStatus: "PENDING",
    addressStatus: "PENDING",
    sanctionsStatus: "PENDING",
    mediaStatus: "PENDING",
    politicalExposure: "PENDING",
  },
  bsa: { risk: "High", score: 7 },
};

export const bsaSucessResponse = [
  { position: 1, questionId: "usCitizen", answer: "yes" },
  { position: 2, questionId: "countryOfOrigin", answer: null },
  { position: 3, questionId: "milesAway", answer: "yes" },
  { position: 4, questionId: "hearAbout", answer: null },
  { position: 5, questionId: "individualIncome", answer: "yes" },
  { position: 6, questionId: "householdIncome", answer: "yes" },
  { position: 7, questionId: "wireTransfersDomestic", answer: "yes" },
  { position: 8, questionId: "wireTransfersInternational", answer: "yes" },
  { position: 9, questionId: "cashTransactions", answer: "yes" },
  { position: 10, questionId: "anotherBank", answer: "no" },
  { position: 11, questionId: "otherBankName", answer: null },
  { position: 12, questionId: "mobileOrATMDeposit", answer: "yes" },
];

export const bsaQuestions = {
  _: {
    thresholds: [
      {
        op: ">=",
        val: 7,
        risk: "High",
      },
      {
        op: ">=",
        val: 5,
        risk: "Moderate",
      },
      {
        risk: "Low",
      },
    ],
  },
  hearAbout: {
    text: "How did you hear about Central Bank?",
    type: "string",
    order: 3,
    regex: "^[a-zA-Z0-9- ']*$",
    default: "",
    subtype: "text",
    required: true,
    dependsOn: {
      milesAway: "no",
    },
    maxLength: 255,
  },
  milesAway: {
    enum: ["yes", "no"],
    text: "Does at least one account owner live within 50 miles of a Central Bank office?",
    type: "string",
    order: 2,
    score: {
      no: 2,
    },
    default: "yes",
    subtype: "enum",
    required: true,
  },
  usCitizen: {
    enum: ["yes", "no"],
    text: "Are all account owners US citizens?",
    type: "string",
    order: 0,
    score: {
      no: 2,
    },
    default: "yes",
    subtype: "enum",
    required: true,
  },
  anotherBank: {
    enum: ["yes", "no"],
    text: "Will you maintain a checking account at another bank?",
    type: "string",
    order: 9,
    score: {
      yes: 1,
    },
    default: "no",
    subtype: "enum",
    required: true,
  },
  otherBankName: {
    text: "What is the name of the bank?",
    type: "string",
    order: 10,
    regex: "^[a-zA-Z0-9- ']*$",
    default: "",
    subtype: "text",
    required: true,
    dependsOn: {
      anotherBank: "yes",
    },
    maxLength: 100,
  },
  countryOfOrigin: {
    text: "What is your country of origin?",
    type: "string",
    order: 1,
    score: {
      US: 0,
      default: 0,
    },
    default: "US",
    subtype: "country",
    required: false,
    dependsOn: {
      usCitizen: "no",
    },
  },
  householdIncome: {
    enum: ["yes", "no"],
    text: "Is your household income greater than $50,000?",
    type: "string",
    order: 5,
    score: {
      no: 1,
    },
    default: "yes",
    subtype: "enum",
    required: true,
  },
  cashTransactions: {
    enum: ["yes", "no"],
    text: "Do you expect cash transactions in excess of $2,500 per month?",
    type: "string",
    order: 8,
    score: {
      yes: 2,
    },
    default: "no",
    subtype: "enum",
    required: true,
  },
  individualIncome: {
    enum: ["yes", "no"],
    text: "Is your individual income greater than $35,000?",
    type: "string",
    order: 4,
    score: {
      no: 1,
    },
    default: "yes",
    subtype: "enum",
    required: true,
  },
  mobileOrATMDeposit: {
    enum: ["yes", "no"],
    text: "Are you planning on using Mobile or ATM Deposits?",
    type: "string",
    order: 11,
    score: {
      yes: 1,
    },
    default: "no",
    subtype: "enum",
    required: true,
  },
  wireTransfersDomestic: {
    enum: ["yes", "no"],
    text: "Do you anticipate 2 or more domestic wire transfers per month?",
    type: "string",
    order: 6,
    score: {
      yes: 2,
    },
    default: "no",
    subtype: "enum",
    required: true,
  },
  wireTransfersInternational: {
    enum: ["yes", "no"],
    text: "Do you anticipate 1 or more international wire transfers per month?",
    type: "string",
    order: 7,
    score: {
      yes: 2,
    },
    default: "no",
    subtype: "enum",
    required: true,
  },
};
