export const initialProductConfiguration = {
  initialDeposit: 100,
  options: [],
  productId: "dfdd41ad-3026-4b87-8ef5-14c1d9147e2a",
};
export const mockSelectedProductCD = {
  id: "dfdd41ad-3026-4b87-8ef5-14c1d9147e2a",
  name: "CD Plus Certificates of Deposit",
  category: "CD",
  sku: "cd-plus-certificates-of-deposit",
  summary: "",
  content:
    "<p><strong>Who’s it for?</strong> Individuals and businesses that have excess funds to invest and will not need access to the funds for the term. As an alternative to a fixed interest rate investment, the CD Plus is for the customer looking to earn a higher rate of interest than a regular savings account and anticipates benefiting from rising interest rates.</p> <ul> <li>$500 minimum to open</li> <li>$50 minimum additional deposits allowed during term</li> <li>Original maturity date remains the...",
  createdAt: "2020-10-07T17:52:10.809Z",
  options: [
    { key: "0", category: "interest_rate_12m", title: "0.36%", value: "0.36" },
    { key: "12m", category: "term", title: "12 Months", value: "12" },
    {
      key: "value_min",
      category: "initial_deposit",
      title: "Minimum Deposit",
      value: "500",
    },
  ],
};

export const listProducts = [
  {
    id: "dd89e068-3d2b-4017-9137-bb807207ec27",
    name: "Classic Savings",
    category: "SAVINGS",
    sku: "classic-savings",
    summary:
      "Everything you could want in a savings account. Classic Savings offers a place to save money, earn interest and get immediate access to your money if needed.",
    content:
      "<p><strong>Classic Savings</strong> gives you the tools to start saving while keeping quick access to your money:</p>\n<ul>\n<li>Variable interest, paid quarterly</li>\n<li>Six (6) preauthorized debits/statement cycle</li>\n<li>Free ATM Card with no ATM Fees*</li>\n<li>Online Banking</li>\n<li>Bankline 24/7</li>\n<li>Direct Deposit</li>\n<li>Online Statements or quarterly paper statements mailed, monthly if electronic transactions</li>\n</ul>\n<p><strong>Additional Information About Classic Savings</strong></p>\n<ul>\n<li>$100 minimum deposit to open account</li>\n<li>$100 minimum balance or $250 average daily balance to avoid fees. If below, $2/statement cycle service charge or free for those 18 and younger</li>\n</ul>\n<p><em>*ATM Card is subject to approval. If you receive an ATM surcharge, bring in or mail your original ATM receipt within 60 days and we will refund the surcharge. Excludes foreign surcharge fees.</em></p>\n<p><em>Service charge subject to Iowa &amp; Local Option sales tax, excluding our South Dakota locations.</em></p>\n",
    createdAt: "2020-10-07T17:51:43.352Z",
    options: [
      {
        id: "cdb01101-f891-4ef9-82f8-e5568d537fd2",
        key: "transfer",
        category: "earnings_paid_type",
        title: "Transfer",
        value: "CheckTransfer",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "56397e49-3636-45c0-87c2-2843193ad155",
        key: "transfer_account_number",
        category: "earnings_transfer_account",
        title: "Account Number",
        value: "",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "068acaa4-4905-428b-bbf7-2de4552330bc",
        key: "transfer_quaterly",
        category: "earning_transfer_frequency",
        title: "Quaterly",
        value: "CheckQuaterly",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "cd516629-423b-4092-8033-34d8c18d151b",
        key: "value_min",
        category: "initial_deposit",
        title: "Minimum Deposit",
        value: "100",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "a2d97fbf-5519-4019-8250-08455b5d2ced",
        key: "atm_only_card",
        category: "product_feature",
        title: "ATM Only Card",
        value: "false",
        lead: "",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "c0005101-ee55-48d9-a8b4-a5192c5fb016",
        key: "bill_pay",
        category: "product_feature",
        title: "Bill Pay",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "228ecc8a-99c1-411c-9f47-bf87290ebe6b",
      },
      {
        id: "8a34f633-5e86-434a-9602-2b940da2fecd",
        key: "e_statements",
        category: "product_feature",
        title: "E-Statements",
        value: "true",
        lead: "Get your bank statements directly on your email",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "228ecc8a-99c1-411c-9f47-bf87290ebe6b",
        key: "mobile_and_online_banking",
        category: "product_feature",
        title: "Mobile & Online Banking",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "639c43e7-b27c-404b-9370-84244b56b2c2",
        key: "mobile_deposits",
        category: "product_feature",
        title: "Mobile Deposits",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "228ecc8a-99c1-411c-9f47-bf87290ebe6b",
      },
      {
        id: "5544777b-53e2-47da-a6f9-90e73a0abdc7",
        key: "paper_statements",
        category: "product_feature",
        title: "Paper Statements",
        value: "false",
        lead: "",
        annotation: "$3/statement",
        parentId: "",
      },
    ],
  },
  {
    id: "e2af65c3-14f2-4626-a129-91abcd267128",
    name: "Money Market Savings",
    category: "SAVINGS",
    sku: "money-market-savings",
    summary:
      "Grow your money faster with the tiered interest of a Money Market Savings, and be assured that you can also access it quickly if necessary",
    content:
      "<p>Aside from tiered interest on your balances, <strong>Money Market</strong> Savings offers the complementary services you need to manage and access your money:</p>\n<ul>\n<li><p>Variable interest, paid monthly based on the following balance tiers:</p>\n<ul>\n<li>$50,000.00 and above</li>\n<li>$25,000.00 – $49,999.99</li>\n<li>$5,000.00 – $24,999.99</li>\n<li>Up to $4,999.99</li>\n</ul>\n</li>\n<li><p>Six (6) preauthorized debits/statement cycle</p>\n</li>\n<li><p>Free ATM Card with No ATM Fees*</p>\n</li>\n<li><p>Online Banking</p>\n</li>\n<li><p>Bankline 24/7</p>\n</li>\n<li><p>Direct Deposit</p>\n</li>\n<li><p>Online Statements or monthly paper statements mailed</p>\n</li>\n</ul>\n<p><strong>Additional Information About Money Market Savings</strong></p>\n<ul>\n<li>$1,000 minimum deposit to open account</li>\n<li>$1,000 minimum balance or $2,500 average daily balance to avoid fees. If below, $10/statement cycle service charge</li>\n</ul>\n<p><em>*ATM Card is subject to approval. If you receive an ATM surcharge, bring in or mail your original ATM receipt within 60 days and we will refund the surcharge. Excludes foreign surcharge fees.</em></p>\n<p><em>Service charge subject to Iowa &amp; Local Option sales tax, excluding our South Dakota locations.</em></p>\n",
    createdAt: "2020-10-07T17:51:48.975Z",
    options: [
      {
        id: "ca44e086-42aa-4dae-8f3f-9d5fe2fe4a6e",
        key: "transfer",
        category: "earnings_paid_type",
        title: "Transfer",
        value: "CheckTransfer",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "792626af-c535-441e-aac7-510350d9522b",
        key: "transfer_account_number",
        category: "earnings_transfer_account",
        title: "Account Number",
        value: "",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "693e6b27-3c4e-422b-9eaa-d9c5f3fdeba3",
        key: "transfer_monthly",
        category: "earning_transfer_frequency",
        title: "Monthly",
        value: "CheckMonthly",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "2b089af3-c028-4048-864e-50800fc290ae",
        key: "value_min",
        category: "initial_deposit",
        title: "Minimum Deposit",
        value: "1000",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "77c71aa3-7016-44d1-9428-d352df84503f",
        key: "atm_only_card",
        category: "product_feature",
        title: "ATM Only Card",
        value: "false",
        lead: "",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "32af1002-69ca-40a1-9033-e4e2d0262a48",
        key: "bill_pay",
        category: "product_feature",
        title: "Bill Pay",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "c5ea1640-2a9d-46b2-a5a9-8cacfd0df70c",
      },
      {
        id: "a2949226-a58f-41c5-9a82-6d1b2759b10a",
        key: "e_statements",
        category: "product_feature",
        title: "E-Statements",
        value: "true",
        lead: "Get your bank statements directly on your email",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "c5ea1640-2a9d-46b2-a5a9-8cacfd0df70c",
        key: "mobile_and_online_banking",
        category: "product_feature",
        title: "Mobile & Online Banking",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "2dac1859-b035-443d-95f9-05a664de88fa",
        key: "mobile_deposits",
        category: "product_feature",
        title: "Mobile Deposits",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "c5ea1640-2a9d-46b2-a5a9-8cacfd0df70c",
      },
      {
        id: "208e70af-d734-413a-b1c6-f1fbee70bf62",
        key: "paper_statements",
        category: "product_feature",
        title: "Paper Statements",
        value: "false",
        lead: "",
        annotation: "$3/statement",
        parentId: "",
      },
    ],
  },
  {
    id: "a4f6f570-3888-49bc-b2e3-c243d6e152eb",
    name: "Platinum Checking",
    category: "CHECKING",
    sku: "platinum-checking",
    summary:
      "With variable interest paid at tiered rates - the higher your balance, the better your rates – Platinum Checking is perfect for when you want to have cash available and make that balance work for you. Platinum Checking rewards your relationship and is free for Emerald Club members and customers who have their first mortgage with us.",
    content:
      "<p><strong>Shamrock Checking</strong> offers more than just interest to account holders. It also provides the same benefits as our other CHECKING accounts combined with free cashier&#39;s checks and money orders:</p>\n<ul>\n<li>Free Shazam®Chek Card* with No ATM Fees**</li>\n<li>Free Online Banking</li>\n<li>Free Online Bill Pay</li>\n<li>Bankline 24/7</li>\n<li>Free Mobile Banking***</li>\n<li>Free Mobile Deposit*</li>\n<li>Free online statements or free monthly statements mailed</li>\n<li>Overdraft Reserve on qualifying accounts*</li>\n<li>Free basic wallet checks, limit 1 box/order</li>\n<li>Free Cashier&#39;s Check/Money Orders – limit 3/month</li>\n</ul>\n<p><strong>Variable interest, paid monthly based on the following balance tiers:</strong></p>\n<ul>\n<li>$50,000.00 and above</li>\n<li>$25,000.00 – $49,999.99</li>\n<li>$10,000.00 – $24,999.99</li>\n<li>Up to $9,999.99</li>\n</ul>\n<p><strong>Additional Information About Platinum Checking</strong></p>\n<ul>\n<li>$100 minimum to open account</li>\n<li>$15,000 minimum consumer relationship, includes deposits and loans, to avoid fees</li>\n<li>If below relationship qualifications, $9.99/statement cycle service charge</li>\n<li>Closed-end consumer loan rate reduction of 0.25% on any new loan.****</li>\n<li>$150 off mortgage origination fees</li>\n<li>0.10% bonus rate on new CDs*****</li>\n<li>Platinum Checking is free for Emerald Club members and customers who have their first mortgage with us</li>\n</ul>\n<p>*Shazam®Chek Card, Mobile Deposit, Overdraft Reserve and Credit Cards are subject to approval.</p>\n<p>**If you receive an ATM surcharge, bring in or mail your original ATM receipt within 60 days and we will refund the surcharge. Excludes foreign surcharge fees. </p>\n<p>***Although Central Bank does not charge for Mobile Banking, standard text messaging and data plan fees from your mobile phone carrier may apply. Please consult your carrier before using Mobile Banking.</p>\n<p>****Rate reduction is not valid with any other promotional offers.</p>\n<p>*****Bonus rate on new CDs is not valid on CD Plus, Rule Breaker CDs or with any other promotional offers.</p>\n<p>Service charge subject to Iowa &amp; Local Option sales tax, excluding our South Dakota locations.</p>\n",
    createdAt: "2020-10-07T17:51:35.602Z",
    options: [
      {
        id: "2e4b5f78-812b-457a-b7cf-d371b50d5197",
        key: "transfer",
        category: "earnings_paid_type",
        title: "Transfer",
        value: "CheckTransfer",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "a690d27a-22da-460b-a94d-0cfa3d24cdb3",
        key: "transfer_account_number",
        category: "earnings_transfer_account",
        title: "Account Number",
        value: "",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "3af71d26-8be7-4098-8017-ed61a2b799bd",
        key: "transfer_monthly",
        category: "earning_transfer_frequency",
        title: "Monthly",
        value: "CheckMonthly",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "99ad689f-b3f3-4b90-825f-c23caca58e87",
        key: "value_min",
        category: "initial_deposit",
        title: "Minimum Deposit",
        value: "100",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "726d5b1f-e096-4491-9f97-05b827130a79",
        key: "bill_pay",
        category: "product_feature",
        title: "Bill Pay",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "c4ea13be-7f75-4c27-b748-b5a449e1b56d",
      },
      {
        id: "277485df-f789-43fc-821d-5191651043e1",
        key: "checks",
        category: "product_feature",
        title: "Checks",
        value: "",
        lead: "",
        annotation: "Can be ordered thru online banking",
        parentId: "",
      },
      {
        id: "ac788c04-3c8a-4f0e-8d2d-4011e6f35a48",
        key: "debit_card",
        category: "product_feature",
        title: "Debit Card",
        value: "true",
        lead: "Shazam®Chek Card",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "82be19ca-2e86-4fe4-a485-0d9eea84fdf8",
        key: "e_statements",
        category: "product_feature",
        title: "E-Statements",
        value: "true",
        lead: "Get your bank statements directly on your email",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "c4ea13be-7f75-4c27-b748-b5a449e1b56d",
        key: "mobile_and_online_banking",
        category: "product_feature",
        title: "Mobile & Online Banking",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "796e762a-29af-4ca1-87bf-02eda98aef3a",
        key: "mobile_deposits",
        category: "product_feature",
        title: "Mobile Deposits",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "c4ea13be-7f75-4c27-b748-b5a449e1b56d",
      },
      {
        id: "281ec6af-fef4-44a0-aa86-64c2d21686b7",
        key: "paper_statements",
        category: "product_feature",
        title: "Paper Statements",
        value: "false",
        lead: "",
        annotation: "$3/statement",
        parentId: "",
      },
    ],
  },
  {
    id: "090f7efd-5b5d-464e-813e-a64975d39496",
    name: "Platinum Money Market Savings",
    category: "SAVINGS",
    sku: "platinum-savings",
    summary:
      "Platinum Money Market Savings is specially designed for our Platinum Money Market Checking customers and accommodates their higher account balances while offering tiered interest for growth in addition to security and liquidity",
    content:
      "<p>With higher tiers of interest than our regular Money Market account, <strong>Platinum Money Market</strong> turns these higher balances into greater growth in addition to providing you with the tools you need to manage your finances:</p>\n<ul>\n<li><p>Variable interest, paid monthly based on the following balance tiers:</p>\n<ul>\n<li>$250,000.00 and above</li>\n<li>$100,000.00 – $249,999.99</li>\n<li>$50,000.00 – $99,999.99</li>\n<li>$10,000 – $49,999.99</li>\n<li>Up to $9,999.99</li>\n</ul>\n</li>\n<li><p>Six (6) preauthorized debits/statement cycle</p>\n</li>\n<li><p>Free ATM Card with No ATM Fees*</p>\n</li>\n<li><p>Online Banking</p>\n</li>\n<li><p>Bankline 24/7</p>\n</li>\n<li><p>Direct Deposit</p>\n</li>\n<li><p>Online Statements or monthly paper statements mailed</p>\n</li>\n</ul>\n<p><strong>Additional Information About Platinum Money Market Savings</strong></p>\n<ul>\n<li>Platinum Checking required</li>\n<li>$10,000 minimum deposit to open account</li>\n<li>$10,000 minimum balance or $25,000 average daily balance to avoid fees. If below, $15 fee/statement cycle service charge</li>\n</ul>\n<p><em>*ATM Card is subject to approval. If you receive an ATM surcharge, bring in or mail your original ATM receipt within 60 days and we will refund the surcharge. Excludes foreign surcharge fees.</em></p>\n<p><em>Service charge subject to Iowa &amp; Local Option sales tax, excluding our South Dakota locations.</em></p>\n",
    createdAt: "2020-10-07T17:51:55.467Z",
    options: [
      {
        id: "6a889d5f-9ff6-4c57-b80f-d87812d2d2de",
        key: "transfer",
        category: "earnings_paid_type",
        title: "Transfer",
        value: "CheckTransfer",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "fd0c81f5-ddac-41f5-b812-0fc42730fd32",
        key: "transfer_account_number",
        category: "earnings_transfer_account",
        title: "Account Number",
        value: "",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "d6e2aa4e-0fa5-4895-804c-e5057a2f0430",
        key: "transfer_monthly",
        category: "earning_transfer_frequency",
        title: "Monthly",
        value: "CheckMonthly",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "bbec36a5-64ae-4a1b-adb2-163933088e22",
        key: "value_min",
        category: "initial_deposit",
        title: "Minimum Deposit",
        value: "10000",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "fc4d808c-b7b7-4521-8f92-43d22f81d198",
        key: "atm_only_card",
        category: "product_feature",
        title: "ATM Only Card",
        value: "false",
        lead: "",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "e4f74328-6bbf-45b0-846d-1f922b46ab8b",
        key: "bill_pay",
        category: "product_feature",
        title: "Bill Pay",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "9babd218-be5a-464d-9853-fd999d481e78",
      },
      {
        id: "04a309b0-02c9-4cc6-ae1d-0dc41a81a0f5",
        key: "e_statements",
        category: "product_feature",
        title: "E-Statements",
        value: "true",
        lead: "Get your bank statements directly on your email",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "9babd218-be5a-464d-9853-fd999d481e78",
        key: "mobile_and_online_banking",
        category: "product_feature",
        title: "Mobile & Online Banking",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "d19e58ec-1e88-427d-ade9-1d04d9b9e989",
        key: "mobile_deposits",
        category: "product_feature",
        title: "Mobile Deposits",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "9babd218-be5a-464d-9853-fd999d481e78",
      },
      {
        id: "def850b2-1017-4435-a1de-ebe2ab7f8f52",
        key: "paper_statements",
        category: "product_feature",
        title: "Paper Statements",
        value: "false",
        lead: "",
        annotation: "$3/statement",
        parentId: "",
      },
    ],
  },
  {
    id: "84a14b4a-64b4-4693-bbcc-a9278a336977",
    name: "Shamrock Checking",
    category: "CHECKING",
    sku: "shamrock-checking",
    summary:
      "Shamrock Checking gives you rewards for maintaining a higher balance. You get variable interest, paid monthly, plus other benefits like free cashier's checks, money orders and more. Just put a little extra in your Shamrock Checking Account and we'll pay you interest. A great way to make your own luck!",
    content:
      "<p><strong>Shamrock Checking</strong> offers more than just interest to account holders. It also provides the same benefits as our other CHECKING accounts combined with free cashier&#39;s checks and money orders:</p>\n<ul>\n<li>Variable interest, paid monthly</li>\n<li>Free Shazam®Chek Card* with No ATM Fees**</li>\n<li>Free Online Banking</li>\n<li>Free Online Bill Pay</li>\n<li>Bankline 24/7</li>\n<li>Free Mobile Banking***</li>\n<li>Free Mobile Deposit*</li>\n<li>Free online statements or $3/statement mailed</li>\n<li>Overdraft Reserve on qualifying accounts*</li>\n<li>First order basic wallet checks free</li>\n</ul>\n<p><strong>Additional Information About Shamrock Checking</strong></p>\n<ul>\n<li>$100 minimum deposit to open account</li>\n<li>$500 minimum balance or $1,000 average daily balance to avoid fees</li>\n<li>If below, $7.99/statement cycle service charge</li>\n</ul>\n<p>*Shazam®Chek Card, Mobile Deposit, Overdraft Reserve and Credit Cards are subject to approval.</p>\n<p>**If you receive an ATM surcharge, bring in or mail your original ATM receipt within 60 days and we will refund the surcharge. Excludes foreign surcharge fees.</p>\n<p>***Although Central Bank does not charge for Mobile Banking, standard text messaging and data plan fees from your mobile phone carrier may apply. Please consult your carrier before using Mobile Banking.</p>\n<p>Service charges subject to Iowa &amp; Local Option sales tax, excluding our South Dakota locations.</p>\n",
    createdAt: "2020-10-07T17:51:28.626Z",
    options: [
      {
        id: "b3d85aae-6174-46a7-bdc3-6849e567539c",
        key: "transfer",
        category: "earnings_paid_type",
        title: "Transfer",
        value: "CheckTransfer",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "4486105c-29b5-4db4-8108-008941c47ab8",
        key: "transfer_account_number",
        category: "earnings_transfer_account",
        title: "Account Number",
        value: "",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "470f4051-4ca5-4fbc-a18f-a4cb5ddddadb",
        key: "transfer_monthly",
        category: "earning_transfer_frequency",
        title: "Monthly",
        value: "CheckMonthly",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "3e9de985-7d1a-4031-a57c-51e6639abf57",
        key: "value_min",
        category: "initial_deposit",
        title: "Minimum Deposit",
        value: "100",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "92932e1b-3a1a-4785-b9b5-cd728cc69ebd",
        key: "bill_pay",
        category: "product_feature",
        title: "Bill Pay",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "3667f0b0-1306-44d9-96d8-2fc72ad2b477",
      },
      {
        id: "37a96f32-7767-4d3f-9426-e72fcf2599df",
        key: "checks",
        category: "product_feature",
        title: "Checks",
        value: "",
        lead: "",
        annotation: "Can be ordered thru online banking",
        parentId: "",
      },
      {
        id: "1f4d2862-2edd-47e2-b8e3-cf7d229983c6",
        key: "debit_card",
        category: "product_feature",
        title: "Debit Card",
        value: "true",
        lead: "Shazam®Chek Card",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "fe0fafc4-35d5-4569-a5f7-e726c41bf5ec",
        key: "e_statements",
        category: "product_feature",
        title: "E-Statements",
        value: "true",
        lead: "Get your bank statements directly on your email",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "3667f0b0-1306-44d9-96d8-2fc72ad2b477",
        key: "mobile_and_online_banking",
        category: "product_feature",
        title: "Mobile & Online Banking",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "3fc02931-d55a-42b1-b9c4-b532ca9f984f",
        key: "mobile_deposits",
        category: "product_feature",
        title: "Mobile Deposits",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "3667f0b0-1306-44d9-96d8-2fc72ad2b477",
      },
      {
        id: "58b715fc-93c0-4f4c-a16f-fc5a45f866e3",
        key: "paper_statements",
        category: "product_feature",
        title: "Paper Statements",
        value: "false",
        lead: "",
        annotation: "$3/statement",
        parentId: "",
      },
    ],
  },
  {
    id: "1a8b1d5b-5601-4706-95ad-6f92f376752e",
    name: "Simple Checking",
    category: "CHECKING",
    sku: "simple-checking",
    summary:
      "Simple Checking means no fees with online statements. And, it means no minimum balance required to maintain the account, access to online banking, bill pay and more. You get the benefits you want.",
    content:
      "<p><strong>Simple Checking</strong> offers numerous benefits for account holders, including:</p>\n<ul>\n<li>$100 minimum deposit to open account</li>\n<li>No minimum balance required</li>\n<li>Free Shazam®Chek Card* with No ATM Fees**</li>\n<li>Free Online Banking</li>\n<li>Free Online Bill Pay</li>\n<li>Bankline 24/7</li>\n<li>Free Mobile Banking***</li>\n<li>Free Mobile Deposit*</li>\n<li>Direct Deposit</li>\n<li>Free online statements or $3/statement mailed</li>\n<li>Overdraft Reserve on qualifying accounts*</li>\n<li>First order basic wallet checks free</li>\n</ul>\n<p>*Shazam®Chek Card, Mobile Deposit, Overdraft Reserve and Credit Cards are subject to approval.</p>\n<p>**If you receive an ATM surcharge, bring in or mail your original ATM receipt within 60 days and we will refund the surcharge. Excludes foreign surcharge fees. </p>\n<p>***Although Central Bank does not charge for Mobile Banking, standard text messaging and data plan fees from your mobile phone carrier may apply. Please consult your carrier before using Mobile Banking.</p>\n<p>Service charge subject to Iowa &amp; Local Option sales tax, excluding our South Dakota locations.</p>\n",
    createdAt: "2020-10-07T17:50:09.510Z",
    options: [
      {
        id: "135b38c9-03f4-4778-961b-464c78dfbac2",
        key: "transfer",
        category: "earnings_paid_type",
        title: "Transfer",
        value: "CheckNone",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "675d5e07-8a07-4dbb-9734-759caae21845",
        key: "transfer_account_number",
        category: "earnings_transfer_account",
        title: "Account Number",
        value: "",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "df46519d-a8ed-4636-aa61-e9e1ade6bd0f",
        key: "transfer_none",
        category: "earning_transfer_frequency",
        title: "none",
        value: "CheckNone",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "7e51f0fe-139a-4b45-a4f9-aec38de4f1aa",
        key: "value_min",
        category: "initial_deposit",
        title: "Minimum Deposit",
        value: "100",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "8d41a0ee-0199-4394-93d5-3641e0822df5",
        key: "0",
        category: "interest_rate",
        title: "0%",
        value: "0",
        lead: "",
        annotation: "",
        parentId: "",
      },
      {
        id: "b81ae119-46eb-49eb-9c9f-3e5a98ac4cd9",
        key: "bill_pay",
        category: "product_feature",
        title: "Bill Pay",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "02777e58-4f03-4a54-bc70-add9f27e9629",
      },
      {
        id: "ca4e17ca-af83-4eb4-ad3c-e9e001a8f3ad",
        key: "checks",
        category: "product_feature",
        title: "Checks",
        value: "",
        lead: "",
        annotation: "Can be ordered thru online banking",
        parentId: "",
      },
      {
        id: "53005bad-ec77-4e33-80ed-deb25b0c3c49",
        key: "debit_card",
        category: "product_feature",
        title: "Debit Card",
        value: "true",
        lead: "Shazam®Chek Card",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "cef38015-f0e3-46e6-b1ca-3fd1af0650ad",
        key: "e_statements",
        category: "product_feature",
        title: "E-Statements",
        value: "true",
        lead: "Get your bank statements directly on your email",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "02777e58-4f03-4a54-bc70-add9f27e9629",
        key: "mobile_and_online_banking",
        category: "product_feature",
        title: "Mobile & Online Banking",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "",
      },
      {
        id: "25388dd9-4741-4213-ba1a-d2ed46b54c68",
        key: "mobile_deposits",
        category: "product_feature",
        title: "Mobile Deposits",
        value: "true",
        lead: "",
        annotation: "Free",
        parentId: "02777e58-4f03-4a54-bc70-add9f27e9629",
      },
      {
        id: "2c5b79a0-e7af-4bfd-afe3-50f251910356",
        key: "paper_statements",
        category: "product_feature",
        title: "Paper Statements",
        value: "false",
        lead: "",
        annotation: "$3/statement",
        parentId: "",
      },
    ],
  },
];
