export const partialResponseSuccess = {
  reference: "SP_REQUEST_0.32516248350478993",
  event: "verification.declined",
  email: "psousa+dev@wearesingular.com",
  country: null,
  verification_data: {
    document: {
      dob: "1989-09-06",
      name: {
        first_name: "John",
        middle_name: null,
        last_name: "Livone",
      },
      selected_type: ["driving_license"],
      supported_types: ["driving_license", "id_card"],
      document_number: "AABBCCDD",
      expiry_date: "2099-09-06",
      issue_date: "1999-10-06",
    },
    address: {
      full_address: "10 Downing St, Westminster, London SW1A 2AA, UK",
      name: {
        first_name: "JOHN",
        middle_name: null,
        last_name: "LIVONE",
      },
      selected_type: ["id_card"],
      supported_types: ["driving_license", "id_card"],
    },
  },
  verification_result: {
    address: {
      address_document: 1,
      match_address_proofs_with_document_proofs: 1,
      full_address: 1,
      name: 1,
      address_document_proof: 1,
      address_document_must_not_be_expired: 1,
      address_document_visibility: 1,
      selected_type: 1,
      address_document_country: 1,
    },
    document: {
      document_visibility: 1,
      dob: 1,
      document_proof: 1,
      document_country: 1,
      name: 1,
      document: 1,
      document_must_not_be_expired: 1,
      selected_type: 0,
    },
  },
  info: {
    agent: {
      is_desktop: false,
      is_phone: false,
      useragent: "axios/0.19.0",
      device_name: "0",
      browser_name: "",
      platform_name: "",
    },
    geolocation: {
      host: "85.240.90.235",
      ip: "85.240.90.235",
      rdns: "bl7-90-235.dsl.telepac.pt",
      asn: "3243",
      isp: "Servicos De Comunicacoes E Multimedia S.A.",
      country_name: "Portugal",
      country_code: "PT",
      region_name: "Lisbon",
      region_code: "11",
      city: "Lisbon",
      postal_code: "1150-244",
      continent_name: "Europe",
      continent_code: "EU",
      latitude: "30.7174",
      longitude: "-1.1321",
      metro_code: "",
      timezone: "Europe/Lisbon",
    },
  },
  declined_reason: "Document doesnt match the provided options",
  declined_codes: ["SPDR13"],
};

export const errorResponse = {
  reference: "5674563141",
  event: "request.invalid",
  error: {
    service: "address",
    key: null,
    message: "The address.name must be an array.",
  },
  email: null,
  country: null,
};

export const acceptedResponse = {
  reference: "5674563147",
  event: "verification.accepted",
  email: "john@wearesingular.com",
  country: "US",
  verification_data: {
    document: {
      issue_date: "1990-01-01",
      selected_type: ["id_card"],
      supported_types: [
        "id_card",
        "passport",
        "driving_license",
        "credit_or_debit_card",
      ],
    },
    address: {
      full_address: "Candyland Avenue",
      selected_type: ["utility_bill"],
      supported_types: [
        "utility_bill",
        "driving_license",
        "bank_statement",
        "envelope",
        "id_card",
        "passport",
        "rent_agreement",
        "employer_letter",
        "insurance_agreement",
        "tax_bill",
      ],
    },
    background_checks: {
      dob: "1990-01-01",
      name: {
        last_name: "John",
        first_name: "Doe",
      },
    },
  },
  verification_result: {
    background_checks: 1,
    address: {
      partial_address_match_with_id_and_utility_bill: 1,
      full_address: 1,
      address_document_visibility: 1,
      address_document_must_not_be_expired: 1,
      address_document: 1,
      address_document_country: 1,
      selected_type: 1,
    },
    document: {
      issue_date: 1,
      document_visibility: 1,
      document_must_not_be_expired: 1,
      document: 1,
      document_country: 1,
      selected_type: 1,
    },
    face: 1,
  },
  info: {},
};

export const declinedResponse = {
  reference: "5674563147",
  event: "verification.declined",
  email: "john@wearesingular.com",
  country: "US",
  verification_data: {},
  verification_result: {
    document: {
      face_on_document_matched: 0,
      document_country: 1,
      document_visibility: 1,
      selected_type: 1,
      document_must_not_be_expired: 0,
      document: 0,
      document_number: 1,
      document_proof: 1,
      expiry_date: 1,
      dob: 1,
      customer_looks_like_x_year_old: 1,
      name: null,
    },
    face: 0,
  },
  info: {},
  declined_reason: "Document originality could not be verified",
  declined_codes: ["SPDR15", "SPDR01", "SPDR17", "SPDR06"],
};
